---
title: "Statistical Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = TRUE)
library(tidyverse)
```

```{r}
act_scores <- read_csv("data/Wisconsin ACT Scores 2022.csv")
report_cards <- read_csv("data/2021-2022 Wisconsin School Report Cards.csv")

colnames(act_scores) <- make.names(colnames(act_scores))
colnames(report_cards) <- make.names(colnames(report_cards))

act_data <- act_scores %>%
  select(School.Name = School, Avg.Score)

report_card_data <- report_cards %>%
  select(School.Name, Overall.Accountability.Score)

merged_data <- inner_join(act_data, report_card_data, by = "School.Name")

cleaned_data <- merged_data %>%
  mutate(
    Avg.Score = as.numeric(Avg.Score),
    Overall.Accountability.Score = as.numeric(Overall.Accountability.Score)
  ) %>%
  drop_na(Avg.Score, Overall.Accountability.Score)  

head(cleaned_data)

```

```{r}
correlation <- cor.test(cleaned_data$Avg.Score, cleaned_data$Overall.Accountability.Score)

regression_model <- lm(Overall.Accountability.Score ~ Avg.Score, data = cleaned_data)


conf_interval <- confint(regression_model, level = 0.95)

list(
  correlation = correlation,
  regression_summary = summary(regression_model),
  confidence_interval = conf_interval
)
```



```{r}
ggplot(cleaned_data, aes(x = Avg.Score, y = Overall.Accountability.Score)) +
  geom_point() +
  geom_smooth(method = "lm", color = "blue") +
  labs(
    title = "Relationship Between ACT Scores and Accountability Scores",
    x = "Average ACT Score",
    y = "Overall Accountability Score"
  ) +
  theme_minimal()
```

